kind: Kustomization

resources:
- ../../dev/gpu-optimizer

images:
- name: aibrix/metadata-service
  newName: aibrix-container-registry-cn-beijing.cr.volces.com/aibrix/metadata-service
  newTag: nightly